import { PermissionCompany } from './types';

export const STATIC_SECURITY_GROUPS: Record<PermissionCompany, string[]> = {
  [PermissionCompany.AGAP2IT]: [
    "FS-AGAP2-00-Administrativo-Consultores Internacional Agap2",
    "FS-AGAP2-00-Administrativo-HIQ-Travel-FCC",
    "FS-AGAP2-00-Administrativo-HIQ-Travel-FSCC",
    "FS-AGAP2-00-Administrativo-HIQ-Travel",
    "FS-AGAP2-00-Administrativo",
    "FS-AGAP2-01-Gestão de Frota",
    "FS-AGAP2-01-Gestão de Pessoal-FFJD",
    "FS-AGAP2-01-Gestão de Pessoal",
    "FS-AGAP2-01-Gestão de Pessoal-Salarios-Confidencial",
    "FS-AGAP2-01-Gestão de Pessoal-Salarios",
    "FS-AGAP2-02-Gestão de Clientes-PASTACLIENTES",
    "FS-AGAP2-02-Gestão de Clientes",
    "FS-AGAP2-03-Gestão de Fornecedores",
    "FS-AGAP2-04-Contabilidade",
    "FS-AGAP2-04-Contabilidade-Tesouraria",
    "FS-AGAP2-05-Administrativo de Pessoal",
    "FS-AGAP2-06-Independentes",
    "FS-AGAP2-07-Legal"
  ],
  [PermissionCompany.AGAP2IND]: [
    "FS-AGAP2-00-Administrativo-Consultores Internacional Agap2",
    "FS-AGAP2-00-Administrativo-HIQ-Travel-FCC",
    "FS-AGAP2-00-Administrativo-HIQ-Travel",
    "FS-AGAP2-00-Administrativo",
    "FS-AGAP2-01-Gestão de Frota",
    "FS-AGAP2-01-Gestão de Pessoal",
    "FS-AGAP2-01-Gestão de Pessoal-Salarios-Confidencial",
    "FS-AGAP2-02-Gestão de Clientes",
    "FS-AGAP2-03-Gestão de Fornecedores",
    "FS-AGAP2-04-Contabilidade",
    "FS-AGAP2-05-Administrativo de Pessoal",
    "FS-AGAP2-06-Independentes",
    "FS-AGAP2-07-Legal"
  ],
  [PermissionCompany.KCSIT]: [
    "FS-KCSIT-00-Administrativo",
    "FS-KCSIT-01-Gestão de Pessoal-Gestão de Frota",
    "FS-KCSIT-01-Gestão de Pessoal",
    "FS-KCSIT-01-Gestão de Pessoal-Salários-Confidencial",
    "FS-KCSIT-01-Gestão de Pessoal-Salários",
    "FS-KCSIT-02-Gestão de Clientes-",
    "FS-KCSIT-03-Gestão de Fornecedores",
    "FS-KCSIT-04-Contabilidade",
    "FS-KCSIT-05-Administrativo de Pessoal",
    "FS-KCSIT-06-Independentes",
    "FS-KCSIT-07-Legal"
  ],
  [PermissionCompany.ADENTIS]: [
    "FS-ADENTIS-00-Administrativo",
    "FS-ADENTIS-01-Gestão de Frota",
    "FS-ADENTIS-01-Gestao de Pessoal",
    "FS-ADENTIS-01-Gestão de Pessoal-Salarios-Confidencial",
    "FS-ADENTIS-01-Gestão de Pessoal-Salários",
    "FS-ADENTIS-02-Gestao de Clientes",
    "FS-ADENTIS-03-Gestão de Fornecedores",
    "FS-ADENTIS-04-Contabilidade",
    "FS-ADENTIS-05-Administrativo de Pessoal",
    "FS-ADENTIS-12-Independentes",
    "FS-ADENTIS-14-Legal"
  ],
  [PermissionCompany.ATS4IT_BE]: [
    "FS-ATS4IT-08-Operacional-04-Marketing",
    "FS-ATS4IT-00-Arquivo",
    "FS-ATS4IT-01-Administrativo",
    "FS-ATS4IT-02-Gestão de Clientes",
    "FS-ATS4IT-03-Gestão de Fornecedores",
    "FS-ATS4IT-04-Contabilidade",
    "FS-ATS4IT-05-Administrativo de Pessoal",
    "FS-ATS4IT-07-Legal",
    "FS-ATS4IT-08-Operacional",
    "FS-ATS4IT-09-DRH"
  ],
  [PermissionCompany.ATS4IT_DK]: [
    "FS-ATS4IT-08-Operacional-04-Marketing",
    "FS-ATS4IT-00-Arquivo",
    "FS-ATS4IT-01-Administrativo",
    "FS-ATS4IT-02-Gestão de Clientes",
    "FS-ATS4IT-03-Gestão de Fornecedores",
    "FS-ATS4IT-04-Contabilidade",
    "FS-ATS4IT-05-Administrativo de Pessoal",
    "FS-ATS4IT-07-Legal",
    "FS-ATS4IT-08-Operacional",
    "FS-ATS4IT-09-DRH"
  ],
  [PermissionCompany.BEE_ENGINEERING]: [
    "FS-BEE-00-Administrativos",
    "FS-BEE-05-Documentos-07-DocumentosOficiais",
    "FS-BEE-05-Documentos",
    "FS-BEE-08-RH_03_Processos_IEFP-R",
    "FS-BEE-08-RH_03_Processos_IEFP-RW",
    "FS-BEE-08-RH-R",
    "FS-BEE-08-RH-RW",
    "FS-BEE-10-Gestão de Pessoal-Gestão de Frota",
    "FS-BEE-10-Gestão de Pessoal",
    "FS-BEE-10-Gestão de Pessoal-Salarios-Confidencial",
    "FS-BEE-10-Gestão de Pessoal-Salários",
    "FS-BEE-11-Gestão de Clientes",
    "FS-BEE-12-Gestão de Fornecedores",
    "FS-BEE-13-Contabilidade",
    "FS-BEE-14-Administrativo de Pessoal",
    "FS-BEE-16-Independentes",
    "FS-BEE-17-Legal"
  ],
  [PermissionCompany.CODEWIN]: [
    "FS-CodeWin-00-Administratorivos",
    "FS-CodeWin-10-Gestão de Pessoal-Gestão de Frota",
    "FS-CodeWin-10-Gestão de Pessoal",
    "FS-CodeWin-10-Gestão de Pessoal-Salários-Confidencial",
    "FS-CodeWin-10-Gestão de Pessoal-Salários",
    "FS-CodeWin-11-Gestão de Clientes",
    "FS-CodeWin-12-Gestão de Fornecedores",
    "FS-CodeWin-13-Contabilidade",
    "FS-CodeWin-14-Administrativo de Pessoal",
    "FS-CodeWin-15-Independentes",
    "FS-CodeWin-16-DQAG",
    "FS-CodeWin-17-Legal"
  ],
  [PermissionCompany.MOONGY]: [
    "FS-SOWIN-00-Administrativo",
    "FS-SOWIN-01-Gestão de Frota",
    "FS-SOWIN-01-Gestão de Pessoal",
    "FS-SOWIN-01-Gestão de Pessoal-Salarios-Confidencial",
    "FS-SOWIN-01-Gestão de Pessoal-Salarios",
    "FS-SOWIN-02-Gestão de Clientes-PASTACLIENTES",
    "FS-SOWIN-02-Gestão de Clientes",
    "FS-SOWIN-03-Gestão de Fornecedores",
    "FS-SOWIN-04-Contabilidade",
    "FS-SOWIN-04-Contabilidade-Tesouraria",
    "FS-SOWIN-05-Administrativo de Pessoal",
    "FS-SOWIN-06-Independentes",
    "FS-SOWIN-07-Legal"
  ],
  [PermissionCompany.RECODME_ES]: [
    "FS-RECODME-01-Minutas",
    "FS-RECODME-02-Criacao utilizadores",
    "FS-RECODME-03-Clientes",
    "FS-RECODME-04-Faturacao ES",
    "FS-RECODME-05-Documentacao oficial",
    "FS-RECODME-06-Pessoal",
    "FS-RECODME-07-Fornecedores",
    "FS-RECODME-08-Contabilidade",
    "FS-RECODME-09-ContingentWorker",
    "FS-RECODME-10-ProcessosDeLegalização",
    "FS-Spain"
  ],
  [PermissionCompany.SOWIN_ES]: [
    "FS-SowinES-01-Minutas",
    "FS-SowinES-02-Criacao utilizadores",
    "FS-SowinES-03-Clientes",
    "FS-SowinES-04-Faturacao",
    "FS-SowinES-05-Documentacao oficial",
    "FS-SowinES-06-Pessoal",
    "FS-SowinES-07-Fornecedores",
    "FS-SowinES-08-Contabilidade",
    "FS-SowinES-09-ContingentWorker",
    "FS-SowinES-10-ProcessosDeLegalização"
  ],
  [PermissionCompany.TEAM_IT]: [
    "FS-TEAMIT-00-Administrativo",
    "FS-TEAMIT-10-Gestao_de_Pessoal-Gestao_Frota",
    "FS-TEAMIT-10-Gestao_de_Pessoal",
    "FS-TEAMIT-10-Gestao_de_Pessoal-Salarios-Confidencial",
    "FS-TEAMIT-10-Gestao_de_Pessoal-Salarios",
    "FS-TEAMIT-11-Gestao_de_Clientes",
    "FS-TEAMIT-12-Gestao_de_Fornecedores",
    "FS-TEAMIT-13-Contabilidade",
    "FS-TEAMIT-14-Administrativo_de_Pessoal",
    "FS-TEAMIT-15-Independentes",
    "FS-TEAMIT-17-Legal"
  ]
};
